### ISSUE TITLE
Raw Config 突然失效

### ISSUE THREAD

**Issue by IceLitty** [Fndroid/clash-config-builder#6]
时间戳：2020-04-25
模式：Local Mode
Raw Config 样例：
```yaml
Proxy Group:
  - name: Test
    type: select
    proxies:
      - DIRECT
Rule:
  - DOMAIN-KEYWORD,paypal,Test
```

本次突然想要去更新订阅，结果发现左侧本应出现的代理组消失了，用上述简单的测试例子也不行，啥情况
